# Generated by Django 5.0.6 on 2024-08-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
